# Generated by Django 3.0.2 on 2020-01-22 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='med',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='med', to=settings.AUTH_USER_MODEL),
        ),
    ]
