# Generated by Django 3.0.2 on 2020-01-21 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedService',
            fields=[
                ('med_id', models.CharField(default='', max_length=8, unique=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='service', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('specialty', models.IntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')], default=1)),
                ('specialty_desc', models.TextField()),
                ('province', models.IntegerField(choices=[(1, 'San José'), (2, 'Alajuela'), (3, 'Heredia'), (4, 'Cartago'), (5, 'Guanacaste'), (6, 'Puntarenas'), (7, 'Limón')], default=1)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPhones',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='phone', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='role', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.IntegerField(choices=[(1, 'Paciente'), (2, 'Médico')], default=1)),
            ],
        ),
    ]
