# Generated by Django 3.0.2 on 2020-01-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medservice',
            name='specialty',
            field=models.IntegerField(choices=[(1, 'Anatomía Patológica'), (2, 'Alergología'), (3, 'Cardiología'), (4, 'Dermatología'), (5, 'Endocrinilogía'), (6, 'Gastroenterología'), (7, 'Geriatría'), (8, 'Hematología'), (9, 'Enfermedades infecciosas'), (10, 'Neumología'), (11, 'Neurología'), (12, 'Oftalmología'), (13, 'Otorrinolaringología'), (14, 'Pediatría'), (15, 'Psiquiatría'), (16, 'Rehabilitación'), (17, 'Reumatología'), (18, 'Traumatología')], default=1),
        ),
    ]
