# Generated by Django 3.0.2 on 2020-01-18 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.IntegerField(choices=[(1, 'Paciente'), (2, 'Médico')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='medservice',
            name='med_id',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
    ]
